{% set name = "ipymagic" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a60a20c89b6b58c83df510974f2961c884f54523ba212c16b4f470faba5c64f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ipython >=7.12.0
    - pip
    - python
  run:
    - ipython >=7.12.0
    - python

test:
  imports:
    - ipymagic

about:
  home: https://ipymagic.readthedocs.io/en/latest/index.html
  license: MIT
  license_family: MIT
  license_file: 
  summary: run python with virtualenv in 'ipython'
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
